added atma.io solution + user
wbcsd/pact-catalog pull request #28
Opened 2023-05-27 21:32 UTC by gse-atma-dev

This update introduces our solution 'atma.io', laying the groundwork for the future inclusion of conformance tests.

2023-05-29 11:58 UTC, raimundo-henriques requested changes
@gse-atma-dev Thank you for your submission!

Both the `solution-id` and the `user-id` must contain only letters, numbers, and dashes. 

Can you please replace the underscores (`_`) by dashes (`-`)?

Please see the inline comments.

cc. @prasadt1 
Thank you,

2023-05-29 11:58 UTC, raimundo-henriques commented on catalog/solutions/atma_io/2.0.1/solution.json
> +  "id": "atma_io",
```suggestion
  "id": "atma-io",
```

2023-05-29 11:58 UTC, raimundo-henriques commented on catalog/users/atma_io.json
> +  "id": "atma_io",
```suggestion
  "id": "atma-io",
```

2023-05-29 11:58 UTC, raimundo-henriques commented on catalog/solutions/atma_io/2.0.1/solution.json
> +  "provider": "atma_io",
```suggestion
  "provider": "atma-io",
```

2023-05-29 12:01 UTC, raimundo-henriques commented on catalog/users/atma_io.json
> +  "website": "https://www.atma.io/"
You might want to add the optional field

```
"logo": "<url-to-your-logo>"
```

That ensures that in your logo is displayed in the collaborators page.

I am sorry that the possibility of adding the "logo" field was not explicit in the documentation. I have updated it meanwhile.

2023-05-31 15:16 UTC, raimundo-henriques reviewed
@gse-atma-dev  Thank you for your submission!

We took the liberty to go ahead and fix some minor syntactical problems: since the use of underscores is not allowed by the catalog's syntax, we replaced them by dashes. 

Can you please review the changes?

Also, we strongly recommend adding a logo to your user `json`. Please see the inline comment.

Thank you,
Best,
cc @prasadt1

2023-05-31 15:16 UTC, raimundo-henriques commented on catalog/users/atma-io.json
> +  "website": "https://www.atma.io/"
You might want to add the optional field
```
"logo": "<url-to-your-logo>"
```
That ensures that in your logo is displayed in the collaborators page.

I am sorry that the possibility of adding the "logo" field was not explicit in the documentation. I have updated it meanwhile.

2023-05-31 15:16 UTC, raimundo-henriques reviewed
@gse-atma-dev  Thank you for your submission!

We took the liberty to go ahead and fix some minor syntactical problems: since the use of underscores is not allowed by the catalog's syntax, we replaced them by dashes. 

Can you please review the changes?

Also, we strongly recommend adding a logo to your user `json`. Please see the inline comment.

Thank you,
Best,
cc @prasadt1

2023-07-05 11:09 UTC, gse-atma-dev commented
@raimundo-henriques Sorry for the delay and thank you for making the changes to the solution name.
As requested we added the logo and also added the results from the first conformance test with cirrus-nexus. 

Will add the result of the second compliance test (as soon as it finalized) via a second PR.

2023-07-05 12:25 UTC, raimundo-henriques requested changes
Thank you very much for the changes. There are, however, a couple of issues that still need fixing (but which are easy to fix):
- The `"logo"` field belongs in the `atma-io.json` file, rather than on the `solution.json`. Please see my inline suggestions on how to fix these;
- The conformance test result json is missing a comma, please see my inline suggestion;
- The version of the Pathfinder Tech Specs tested must be either `"1.0.1"` or `"2.0.0"`, please see my inline suggestions.
Thank you for your cooperation!

2023-07-06 12:15 UTC, gse-atma-dev commented
hi, thanks for checking

I added your suggestions but the validation for the version in the pipeline seems now to fail again (I think it does not fail with version 2.0.1, see other PR from true carbon)

2023-07-07 05:31 UTC, gse-atma-dev commented
ah thank you, yes I think if everything is good from your side I think we can merge it

Thanks

2023-07-10 09:48 UTC, raimundo-henriques approved these changes

2023-07-11 06:09 UTC, gse-atma-dev commented
The Vercel deployment action is failing, do we have to resolve this before merging the PR? can you merge it or do we have to do this?

2023-07-11 08:20 UTC, raimundo-henriques commented
Hello again @gse-atma-dev,
That's just because the `main` branch your branch is based on is already outdated, so Vercel's preview will break when trying to build it. This will be solved on merge, which will happen very soon!

Thank you!

2023-07-11 08:21 UTC, merged