feat: carbmee test result
wbcsd/pact-catalog pull request #92
Opened 2023-12-11 08:40 UTC by KushKan0402

2023-12-11 10:35 UTC, raimundo-henriques requested changes
Thank you for the PR, @KushKan0402,

The solutions' versions must have three digits (to conform with semver).
Please see my inline suggestions (and correct them accordingly). 

Please note also that the `solution_id` and the `version` must remain consistent once you add your solutions to the catalog. 

Thank you!
@prasadt1

2023-12-11 10:35 UTC, raimundo-henriques commented on catalog/conformance-tests/result-carbmee-001.json
> +    "version": "1.0"
```suggestion
    "version": "1.0.0"
```

2023-12-11 10:35 UTC, raimundo-henriques commented on catalog/conformance-tests/result-carbmee-001.json
> +    "version": "1.0"
```suggestion
    "version": "1.0.0"
```

2023-12-12 11:03 UTC, prasadt1 commented
@KushKan0402 - can you pelase also add the solution json for your solution? Thanks! Refer [this](https://github.com/wbcsd/pact-catalog/blob/main/CONTRIB_SOLUTION.md) resource. 

Cc: @raimundo-henriques

2023-12-12 11:05 UTC, KushKan0402 commented
Hi Prasad,
Thanks for the update. I will add the solution.json as per the requirements and update my pull request.
Regards,
Kushagra
________________________________
From: PRASAD TILLOO ***@***.***>
Sent: Tuesday, December 12, 2023 7:03 PM
To: wbcsd/pact-catalog ***@***.***>
Cc: Kushagra Kanodia ***@***.***>; Mention ***@***.***>
Subject: Re: [wbcsd/pact-catalog] feat: carbmee test result (PR #92)


@KushKan0402<https://github.com/KushKan0402> - can you pelase also add the solution json for your solution? Thanks! Refer this<https://github.com/wbcsd/pact-catalog/blob/main/CONTRIB_SOLUTION.md> resource.

Cc: @raimundo-henriques<https://github.com/raimundo-henriques>

—
Reply to this email directly, view it on GitHub<https://github.com/wbcsd/pact-catalog/pull/92#issuecomment-1851817505>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCMGLQJMYT7HX7TGAM3MV23YJA2Y3AVCNFSM6AAAAABAPLYVRKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJRHAYTONJQGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-12-13 09:43 UTC, prasadt1 commented
@KushKan0402 - Thanks for your response. Can you kindly submit this sooner as CarbMee and Misrosoft are blocked because of this pending solution submission?

Appreciate your quick support here.

Cc: @raimundo-henriques

2023-12-13 11:07 UTC, KushKan0402 commented
Hi Prasad,
I recently updated the PR and it still shows failing. Can u recommend me what issues need to be addressed.
Regards,
Kushagra
________________________________
From: PRASAD TILLOO ***@***.***>
Sent: Wednesday, December 13, 2023 5:43 PM
To: wbcsd/pact-catalog ***@***.***>
Cc: Kushagra Kanodia ***@***.***>; Mention ***@***.***>
Subject: Re: [wbcsd/pact-catalog] feat: carbmee test result (PR #92)


@KushKan0402<https://github.com/KushKan0402> - Thanks for your response. Can you kindly submit this sooner as CarbMee and Misrosoft are blocked because of this pending solution submission?

Appreciate your quick support here.

Cc: @raimundo-henriques<https://github.com/raimundo-henriques>

—
Reply to this email directly, view it on GitHub<https://github.com/wbcsd/pact-catalog/pull/92#issuecomment-1853581073>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCMGLQNSHJEVL4RF4N2H3ZLYJF2FZAVCNFSM6AAAAABAPLYVRKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJTGU4DCMBXGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-12-13 11:08 UTC, prasadt1 approved these changes

2023-12-13 11:08 UTC, merged